= Supported features
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.9.0
:revdate: 2026-01-23
:imagesdir: ./images
:toc: preamble

[frame="none",grid="none"]
|====
a|[.small]#Author: {author}, version: {revnumber}, date: {revdate}#
|====

Previous chapter: xref:4.output-target.adoc[Output target]

=== DML operations

The following operations are supported:

- INSERT operation (including multiple row INSERT, but not direct path -– INSERT `/\*+append*/`);
- UPDATE operation;
- DELETE operation (including multiple row DELETE).

=== Table parameters

Tables with the following parameters are supported:

- null/not null columns;
- invisible (hidden) columns;
- columns with null and default values;
- up to 1000 columns (database maximum till 21c);
- row chaining/migration;
- partial rollbacks (rollback to savepoint);
- partitioned tables;
- tables with rowdependencies;
- BASICFILE LOBs.

Transactions that are rolled back aren't processed.

Transactions are processed as soon as they're committed (not earlier).

Every transaction is tracked since every transaction can eventually contain a DML operation of a tracked table.

=== Column types

List of supported column types (with internal database codes):

- 1 –- varchar2/nvarchar2 (including out of row stored as LOB), supported <<supported-character-sets,character sets>>;
- 2 –- number/float;
- 12 –- date;
- 23 –- raw;
- 58 -- xmltype (full for clob storage, experimental status for binary storage, not supported for 23c);
- 96 –- char/nchar (list of supported character sets);
- 100 –- binary_float;
- 101 –- binary_double;
- 112 -- clob;
- 113 -- blob;
- 180 –- timestamp;
- 181 –- timestamp with time zone;
- 182 -- interval year to month;
- 183 -- interval day to second;
- 208 -- urowid;
- 231 –- timestamp with local time zone;
- 252 -- boolean.

Every time a column with unsupported type is processed, `"?"` is used as the value.

=== DDL operations

Changes in the schema are supported.

OpenLogReplicator treats DDL operations as DML operations being executed on system tables.
Some system tables are also tracked for changes.

Whenever a DDL command appears in the redo log, the transaction contained two elements:

- the SQL text of the DDL command (which can be sent to output);

- a sequence of DML commands on system tables (which can be sent to output as well) -- which is processed, and the internal copy of system tables is updated.

The DML commands are parsed, and particular columns are extracted from the system tables and updated in the internal dictionaries.
After all changes from one system transaction are processed, OpenLogReplicator deletes internal dictionaries and creates them again.
If a DDL transaction impacts one of the tables that are tracked for replication, a message would appear in the output stream.

[CAUTION]
====
Some of the DDL commands can be internally divided into many transactions.
For example, there could be one transaction for creating a table and another transaction for creating indexes on that table.
This would mean that the table for some time existed without indexes.
Or primary key.
This could lead to warnings in the OpenLogReplicator log file informing that the table is missing a primary key defined in the configuration files.
In such cases -- ignore the warnings.
====

=== Supported character sets [[supported-character-sets]]

OpenLogReplicator supports many character sets which can be used in the source database.

All character fields are read from the source database in respect to the source character set.
The output message always uses Unicode as character encoding and UTF-8 format.
OpenLogReplicator doesn't perform any left-to-right Unicode character replacements.

For test purposes, the character set conversion can be disabled.
Check the xref:../json/4.format.adoc#char[char] parameter for details.

Full list of supported character sets is: *AL16UTF16*, *AL32UTF8*, AR8ADOS710, AR8ADOS710T, AR8ADOS720, AR8ADOS720T, AR8APTEC715, AR8APTEC715T, AR8ARABICMACS, AR8ASMO708PLUS, AR8ASMO8X, AR8HPARABIC8T, AR8ISO8859P6, AR8MSWIN1256, AR8MUSSAD768, AR8MUSSAD768T, AR8NAFITHA711, AR8NAFITHA711T, AR8NAFITHA721, AR8NAFITHA721T, AR8SAKHR706, AR8SAKHR707, AR8SAKHR707T, AZ8ISO8859P9E, BG8MSWIN, BG8PC437S, BLT8CP921, BLT8ISO8859P13, BLT8MSWIN1257, BLT8PC775, BN8BSCII, CDN8PC863, CEL8ISO8859P14, CL8ISO8859P5, CL8ISOIR111, CL8KOI8R, CL8KOI8U, CL8MACCYRILLICS, CL8MSWIN1251, D7DEC, D7SIEMENS9780X, DK7SIEMENS9780X, E7DEC, E7SIEMENS9780X, EE8ISO8859P2, EE8MACCES, EE8MACCROATIANS, EE8MSWIN1250, EE8PC852, EEC8EUROASCI, EEC8EUROPA3, EL8DEC, EL8ISO8859P7, EL8MACGREEKS, EL8MSWIN1253, EL8PC437S, EL8PC737, EL8PC851, EL8PC869, ET8MSWIN923, HU8ABMOD, HU8CWI2, I7DEC, I7SIEMENS9780X, IN8ISCII, IS8MACICELANDICS, IS8PC861, IW8ISO8859P8, IW8MACHEBREWS, IW8MSWIN1255, IW8PC1507, JA16EUC, JA16EUCTILDE, JA16EUCYEN, JA16SJIS, JA16SJISTILDE, JA16SJISYEN, JA16VMS, KO16KSC5601, KO16KSCCS, KO16MSWIN949, LA8ISO6937, LA8PASSPORT, LT8MSWIN921, LT8PC772, LT8PC774, LV8PC1117, LV8PC8LR, LV8RST104090, N7SIEMENS9780X, N8PC865, NDK7DEC, NE8ISO8859P10, NEE8ISO8859P4, RU8BESTA, RU8PC855, RU8PC866, S7DEC, S7SIEMENS9780X, SE8ISO8859P3, SF7ASCII, SF7DEC, TH8MACTHAIS, TH8TISASCII, TIMESTEN8, TR8DEC, TR8MACTURKISHS, TR8MSWIN1254, TR8PC857, US7ASCII, US8PC437, *UTF8*, VN8MSWIN1258, VN8VN3, WE8DEC, WE8DG, WE8HP, WE8ISO8859P1, WE8ISO8859P15, WE8ISO8859P9, WE8MACROMAN8S, WE8MSWIN1252, WE8NCR4970, WE8NEXTSTEP, WE8PC850, WE8PC858, WE8PC860, WE8ROMAN8, ZHS16CGB231280, ZHS16GBK, ZHS32GB18030, ZHT16BIG5, ZHT16CCDC, ZHT16HKSCS, ZHT16HKSCS31, ZHT16MSWIN950, ZHT32EUC, ZHT32TRIS.

The target character set is always Unicode and UTF-8 format.

Next chapter: xref:6.replication.adoc[Replication]
