= Replication
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.9.0
:revdate: 2026-01-23
:imagesdir: ./images
:toc: preamble

[frame="none",grid="none"]
|====
a|[.small]#Author: {author}, version: {revnumber}, date: {revdate}#
|====

Previous chapter: xref:5.supported-features.adoc[Supported features]

=== Initial schema load

During the first run of replication OpenLogReplicator creates a local copy of the source database schema.
The data dictionary may be huge, and by default only a subset of the data is gathered.
Only schemas which are configured for replication are copied.
Other schemas -- not.

If the user wants to replicate other schemas as well.
For example, the user might stop replication, modify the configuration file, add clauses for other schemas, and start replication again.
In such a case, replication would not start because the dictionary data for added schemas is missing.
A possible workaround would be to delete all checkpoint files and start replication again.

=== Schema changes

The user defines the list of schemas/tables which are replicated.
Both the schema name and username may contain wildcards using regex expressions.

A schema name may not yet exist when replication starts and be created in the future.
OpenLogReplicator would start replicating such a schema when it is created.

Next chapter: xref:7.startup.adoc[Startup]
