= Runtime Error Messages (1xxxx)
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.9.0
:revdate: 2026-01-25
:imagesdir: ./images

[frame="none",grid="none"]
|====
a|[.small]#Author: {author}, version: {revnumber}, date: {revdate}#
|====

Errors related to program execution.

==== code 10001: "file: <file name> - open for read returned: <message>"

The provided file is missing or can't be opened for reading.
Check if the file exists and has the correct permissions.
Verify filesystem integrity and operating system log messages.

==== code 10002: "file: <file name> - lock operation returned: <message>"

Attempt to create an exclusive lock on the file has failed.
Check if another process is running (perhaps another instance of OpenLogReplicator).

[TIP]
====
You can list file handles using operating system `lsof` command.
Refer to operating system documentation about locking files.
====

==== code 10003: "file: <file name> - get metadata returned: <message>"

Reading file metadata failed.
Check if the file is not corrupted.
Verify operating system log messages.

==== code 10004: "file: <file name> - wrong size: <number>"

File size is too large or is empty.
Check if the file is not corrupted.

==== code 10005: "file: <file name> - <number> bytes read instead of <number>"

Read operation processed fewer bytes than expected.
Check if the file system is not corrupted and disk-containing file is available.

==== code 10006: "file: <file name> - open for writing returned: <error>"

The file couldn't be opened for write operation.
If the file didn't exist, it would be created.
Verify if the file exists and has the correct permissions.
Verify directory write permissions if a file is to be created.

==== code 10007: "file: <file name> - <number> bytes written instead of <number>, code returned: <message>"

Write operation processed fewer bytes than expected.
Check if the file system is not corrupted and disk-containing file is available.
Verify disk space availability.

==== code 10046: "file: <file name> - set no cache for file returned: <message>"

Apple/iOS only.
Setting of the redo log file to no cache mode failed.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted.
Check operating system log messages.

==== code 10009: "file: <file name> - failed to open after <number> tries"

The file couldn't be opened after several attempts.
Verify if the file exists and has the correct permissions.
Verify directory read permissions if file is to be read.

==== code 10010: "file: <file name> - delete returned: <error>"

File remove failed.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted and contains correct JSON content.
Verify operating system log messages and filesystem integrity.

==== code 10011: "file: <file name> - seek returned: <error>"

File seek failed.
Verify if the file exists and has the correct permissions.
Verify operating system log messages and filesystem integrity.

==== code 10012: "directory: <directory name> - can't read"

Reading the contents of the directory failed.
Verify if the directory exists and has the correct permissions.
Verify operating system log messages and filesystem integrity.

==== code 10013: "spawning thread: <thread name>"

Thread creation failed.

[TIP]
====
Verify if there is a limit set in the OS related to the number of threads.
====

==== code 10014: "stacktrace for thread: <thread id>"

Stacktrace for thread is printed.
This message is printed when the program is terminated by a signal.

[TIP]
====
Stacktrace can be forced by sending SIGUSR1 signal to the program.
====

==== code 10015: "caught signal: <signal name>"

This message is printed when the program is terminated by a signal.

==== code 10016: "couldn't allocate <number> bytes memory for: <module>"

Memory allocation failed.
Verify if the provided `min-mb` and `max-mb` parameters are correct and match amount of memory available in the operating system.

==== code 10017: "out of memory"

Configured amount of memory doesn't allow processing provided stream of redo log files.
Refer to suggestions for details about reducing xref:../user-manual/9.advanced-topics.adoc#memory-allocation[memory allocation].

[TIP]
====
Increase `max-mb` parameter to allow more memory to be used.
====

==== code 10018: "memory allocation failed: <message>"

Memory allocation from heap failed.
Verify if the host contains enough memory to run the program.
If the problem persists, please report this issue.

[IMPORTANT]
====
Some memory structures are allocated adhoc and not from the pool defined with `min-mb` and `max-mb` parameters.
For example for storing schema (copy of content of database `SYS.*` tables).
This message is printed when such allocation fails.
====

==== code 10019: "binaries are build with no regex implementation, check if you have gcc version >= 4.9"

The code is compiled using the old GCC compiler which technically has regex support, but it is not complete.
Use GCC version 4.9 or newer.

The program starts at startup if regex support actually works.

==== code 10020: "program is run as root, you should never do that"

The program is run as root.
It is not recommended to run the program as root.
Run the program as a normal user.

NOTE: Although technically it should be possible to run a program as root user, this should never be done even for testing environment.
The program is designed to run as a normal user.
Running a root user may cause security issues.
Even for development or test environments, keep the program running as a normal user.

==== code 10021: "database not in ARCHIVELOG mode"

The source database must be running in ARCHIVELOG mode.
Verify if the database is running in xref:../installation/installation.adoc#database-configuration[ARCHIVELOG mode].

==== code 10022: "SUPPLEMENTAL_LOG_DATA_MIN missing

The database is missing minimal supplemental log information.
Verify that the database is xref:../installation/installation.adoc#database-configuration[configured correctly].

==== code 10023: "no data in SYS.V_$DATABASE"

Reading `SYS.V_$DATABASE` returned no data.
Verify that the database user has grants to read `SYS.V_$DATABASE` system table.
Refer to database documentation for more information.

==== code 10024: "can't position by time for standby database"

The database is a standby database.
The database must be a primary database when time defines starting position.
Start replication when the database is primary and later switch to xref:../user-manual/9.advanced-topics.adoc#dataguard[the standby database].

==== code 10025: "can't find scn for: <timestamp>"

The database function `TIMESTAMP_TO_SCN` failed to convert provided timestamp to SCN.
Replication is defined to start from a specific timestamp, but the provided timestamp value is not accepted by the database.
Verify if the timestamp is correct.

==== code 10026: "can't position by relative time for standby database"

The database is a standby database.
The database must be a primary database when relative time defines starting position.
Start replication when the database is primary and later switch to xref:../user-manual/9.advanced-topics.adoc#dataguard[the standby database].

==== code 10027: "can't read any member of group <number>"

For a given group of online redo logs, no file is available to read.
Verify if path mapping is correctly configured and files are available for reading from the location where OpenLogReplicator is running.
Verify file and path permissions/ownership.

==== code 10028: "starting sequence is unknown"

Program started with `offline` reader type but no starting sequence is available.
Verify parameters for replication start.

==== code 10029: "can't find database current scn"

Executing a query to read current SCN from a database failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10030: "getting database sequence for scn: <scn"

Executing a query to read the current database sequence value for provided SCN failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10031: "getting database scn"

The operation of determining the starting SCN failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].
Report this issue if the problem persists.

==== code 10032: "can't get parameter value for <parameter>"

Reading of database parameter failed.
Verify if the parameter exists and has the correct value.

==== code 10033: "can't get property value for <property>"

Reading of database property failed.
Verify if the property exists and has the correct value.

==== code 10034: "grants missing for table <table>"

Verify if the database user has grants to read the provided table.
Refer to database documentation for more information.

[TIP]
====
Verify if the grant script was executed successfully.
====

==== code 10035: "can't read <information> from flashback, provide a valid starting SCN value"

During startup when `online` reader is chosen the full schema must be read from the database.
To achieve full consistency, all database queries use flashback to read the contents of system tables for the provided SCN number.
The flashback query failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

[TIP]
====
Run initial replication of replication during a less active period
====

[TIP]
====
Run initial replication on a copy of the database which is not modified
====

[TIP]
====
Provide starting SCN number less away in time.
The SCN number must be within the retention period of the database.
====

==== code 10036: "failed to find standby redo log files"

The database is running as standby, but the list of standby redo log files couldn't be read from the database.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10037: "failed to find online redo log files"

The list of online redo log files couldn't be read from the database.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10038: "unknown database role: <role>"

Data read from system dictionaries is invalid.
Please report this issue.

==== code 10039: "updating of online redo logs failed for <path>"

Updating the list of online redo log files failed.
Verify if the files exist and have the correct permissions.

==== code 10040: "schema file missing"

Program started with `offline` reader type but no schema file is available.
Verify if the schema file exists and has the correct permissions.

==== code 10041: "table <table> - couldn't find all column sets (<keys>)"

One of the columns defined as a primary key is not present in the table definition.
Verify if the table definition is correct.

==== code 10042: "unsupported NLS_CHARACTERSET value: <value>"

Character set defined in the database is invalid.
Please report this issue.

==== code 10044: "missing location of archived redo logs for offline mode"

When starting with offline mode, it is expected that the checkpoint file contains the location of archived redo logs.
Verify if the checkpoint file contains the location of archived redo logs.

==== code 10045: "resetlogs (<resetlogs>) not found in incarnation list"

The given resetlogs value is not found in the list of available incarnations.
Verify if the resetlogs value is correct.
Verify the content of the checkpoint file.

==== code 10046: "unsupported NLS_NCHAR_CHARACTERSET value: <value>"

National character set defined in the database is invalid.
Please report this issue.

==== code 10047: "archive log processing returned: <message>, code: <number>"

Processing of archived redo log file failed.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted.

==== code 10048: "read archived redo log, code: <number>"

An unknown error appeared during processing of archived redo log file.
Please report this issue.

==== code 10049: "read online redo log, code: <number>"

An unknown error appeared during processing of the online redo log file.
Please report this issue.

==== code 10050: "can't initialize database environment (OCI)"

Initialization of database environment failed.
Check if the database client is installed and configured correctly.

==== code 10051: "OCI: <message>"

Database connection error.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10052: schema file missing

Schema is missing for batch mode.

[TIP]
====
If you don't have an earlier schema but wish to continue having no information about column names and types, try with schemaless mode (`'flags': 2`).
Refer to the documentation for more information about
xref:../user-manual/9.advanced-topics.adoc#schemaless-mode[schemaless mode].
====

==== code 10053: "network receive error"

Network operation of receiving data from a client failed.
Verify if the network is available and if the network is not overloaded.

==== code 10054: "network send error"

Network operation of sending data to a client failed.
Verify if the network is available and if the network is not overloaded.

==== code 10055: "message from client is incomplete (length: <number>, buffer size: <number>)"

The message received from a client is incomplete.
Verify if the network is available and if the network is not overloaded.

==== code 10056: "host disconnected"

The client has closed network connection.
Verify if the network is available and if the network is not overloaded.

==== code 10057: "Kafka: fatal error: <message>, reason: <message>"

Kafka library returned a fatal error.
Verify if the Kafka server is available and if the network is not overloaded.

==== code 10058: "Kafka failed to create configuration"

Kafka configuration can't be created.
Check if the configuration file contains valid content.

==== code 10059: "Kafka message: <message>"

Kafka library returned error during initialization.
Verify provided Kafka parameters.

==== code 10060: "Kafka failed to create producer, message: <message>"

Kafka producer creation failed.
Verify the provided Kafka parameters.

==== code 10061: "network error, errno: <number>, message: <message>"

Network error appeared during sending or receiving data.
Verify if the network is available and if the network is not overloaded.

==== code 10062: "connection to <uri> failed, errno: <number>, message: <message>"

Network connection failed.
Verify if the network is available and if the network is not overloaded.

==== code 10063: "ZeroMQ connect to <uri> failed, message: <message>"

Client can't connect to ZeroMQ server.
Verify if the ZeroMQ server is available and if the network is not overloaded.

==== code 10064: "ZeroMQ bind to <uri> failed, message: <message>"

Server can't bind to ZeroMQ socket.
Verify if the ZeroMQ server is available and if the network is not overloaded.
Verify if another process is not running on the same port.

==== code 10065: "ZeroMQ context creation failed"

Creation of ZeroMQ context failed.
Verify if the ZeroMQ library is installed and available.

==== code 10066: "ZeroMQ initializing socket failed, message: <message>"

Initialization of ZeroMQ socket failed.
Verify if the ZeroMQ library is installed and available.

==== code 10067: "deleting old swap file from previous execution: <path>"

Most likely previous execution of OpenLogReplicator left a file in the swap directory.
The file has been deleted.

==== code 10068: "invalid DBTIMEZONE value: <value>"

Database parameter `DBTIMEZONE` has an invalid value.
Please report this issue.

==== code 10069: "invalid timestamp value: <value>"

Timestamp value is invalid. Please report this issue.

==== code 10070: "invalid environment variable OLR_LOG_TIMEZONE value: <value>"

The value of environment variable `OLR_LOG_TIMEZONE` is invalid.

==== code 10071: "file: <file name> size is not a multiplication of <number>, reading only <number> bytes"

The redo log file size should be a multiplication of <number> bytes. If the file size is not a multiplication of <number> bytes, the file is read partially.

==== code 10072: "writer buffer (parameter "write-buffer-max-mb" = <value>) is too small to fit a message with size: <number>)

The size of the message is larger than the buffer size.
Increase the buffer size ("write-buffer-max-mb") and also maybe the size of the total memory ("max-mb" parameter).
