= Configuration Error Messages (3xxxx)
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.9.0
:revdate: 2026-01-25
:imagesdir: ./images

[frame="none",grid="none"]
|====
a|[.small]#Author: {author}, version: {revnumber}, date: {revdate}#
|====

Parameters defined to start OpenLogReplicator have incorrect values.

==== code 30001: "bad JSON, invalid '<field name>' value: <observed value>, expected <expected value>"

The value of the field is not correct.
Check if the file contains valid content.

==== code 30002: "invalid arguments, run: <binary name> [-v|--version] or [-f|--file CONFIG] default path for CONFIG file is <file name>"

Invalid arguments were passed to the program.
Check if the program was started correctly.

==== code 30005: "invalid value for 'output': <value>"

Syntax error in `output` parameter.
Verify if the parameter is correct.
Probably there is a single `%` character but not followed by proper format.

==== code 30006: "output file is with no rotation: <value> - 'append' must be set to 1"

File name is defined as a static file name without rotation.
For such cases the `append` parameter must be set to 1.

==== code 30007: "output file is with no max file size: <output> - 'max-file-size' must be defined for output with rotation"

File is defined with rotation but no maximum file size is set.
Define `max-file-size` parameter.

==== code 30008: "uri is missing ':' in parameter: <parameter>"

URI is missing a `':'` character.
Verify if the URI is correct.

==== code 30009: "Kafka property '<name>' is defined multiple times"

One of the parameters for Kafka writer is defined twice.

==== code 30010: "Kafka property 'message.max.bytes' is defined, but it is not allowed to be set by user"

This property defines the size of maximum message size.
This parameter is already defined by parameter "max-message-mb" and should not be defined explicitly using Kafka connection parameter.
