= Log Messages Guide
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.9.0
:revdate: 2026-01-25
:imagesdir: ./images

[frame="none",grid="none"]
|====
a|[.small]#Author: {author}, version: {revnumber}, date: {revdate}#
|====

This document describes messages of OpenLogReplicator which are written to the log.
The following message levels are used:

1. *Errors* -- Some functionality is not available, user should review the message and take appropriate action.
In some cases, the program may abort.
Messages can be suppressed by setting the `trace` parameter to `0`.
Details: xref:./1.runtume-error-messages.adoc[euntime errors], xref:./2.data-error-messages.adoc[data errors], xref:./3.configuration-error-messages.adoc[configuration errors], xref:./4.redo-log-error-messages.adoc[redo-log errors], xref:./5.internal-error-messages.adoc[internal errors]

2. *Warnings* -- Something is not correct but may be intentional or not critical.
Messages can be suppressed by setting the `trace` parameter to `1`.
Details: xref:./6.warning-messages.adoc[warnings], xref:./7.internal-warning-messages.adoc[internal warnings].

3. *Information* -- Program status.
Messages can be suppressed by setting the `trace` parameter to `2`.

4. *Debug* -- Debugging information.
Messages can be suppressed by setting the `trace` parameter to `3`.

5. *Trace* -- Detailed information about program internals.
Messages are controlled by the `trace` parameter.
Parameter `log-level` is not relevant for tracing.

[IMPORTANT]
====
By default, all error, warning and info messages are printed -- `trace` parameter is set to value `3`.
====

[TIP]
====
The documentation doesn't discuss _Trace_ messages in detail.
Those messages aren't intended to be used by users.
Format can change without notice.
====
