= Log Messages Guide
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.6.1
:revdate: 2024-06-18
:imagesdir: ./images
:toc: preamble

[frame="none",grid="none"]
|====
a|[.small]#Autor: {author}, version: {revnumber}, date: {revdate}#
|====

This document describes messages of OpenLogReplicator which are written to the log.

== Introduction

The following message levels are used:

1. *Errors* -- Some functionality is not available, user should review the message and take appropriate action.
In some cases, the program may abort.
Messages can be suppressed by setting the `trace` parameter to `0`.

2. *Warnings* -- Something is not correct, but may be intentional or not critical.
Messages can be suppressed by setting the `trace` parameter to `1`.

3. *Information* -- Program status.
Messages can be suppressed by setting the `trace` parameter to `2`.

4. *Debug* -- Debugging information.
Messages can be suppressed by setting the `trace` parameter to `3`.

5. *Trace* -- Detailed information about program internals.
Messages are controlled by the `trace` parameter.
Parameter `log-level` is not relevant for tracing.

IMPORTANT: By default, all error, warning and info messages are printed -- `trace` parameter is set to value `3`.

TIP: The documentation doesn't discuss _Trace_ messages in detail.
Those messages aren't intended to be used by users.
Format can change without notice.

== Error Messages

The following messages may be printed during program execution:

=== Runtime errors (1xxxx)

Errors related to program execution.

==== code 10001: "file: <file name> - open returned: <message>"

The provided file is missing or can't be opened for reading.
Check if the file exists and has the correct permissions.
Verify filesystem integrity and operating system log messages.

==== code 10002: "file: <file name> - lock returned: <message>"

Attempt to create an exclusive lock on the file has failed.
Check if another process is running (perhaps another instance of OpenLogReplicator).

TIP: You can list file handles using operating system `lsof` command.
Refer to operating system documentation about locking files.

==== code 10003: "file: <file name> - stat returned: <message>"

Reading file metadata failed.
Check if the file is not corrupted.
Verify operating system log messages.

==== code 10004: "file: <file name> - wrong size: <file size>"

File size is too large or is empty.
Check if the file is not corrupted.

==== code 10005: "file: <file name> - <number> bytes read instead of <number>"

Read operation processed fewer bytes than expected.
Check if the file system is not corrupted and disk-containing file is available.

==== code 10006: "file: <file name> - open for write returned: <error>"

The file couldn't be opened for write.
If the file didn't exist, it would be created.
Verify if the file exists and has the correct permissions.
Verify folder write permissions if a file is to be created.

==== code 10007: "file: <file name> - <number> bytes written instead of <number>, code returned: <message>"

Write operation processed fewer bytes than expected.
Check if the file system is not corrupted and disk-containing file is available.
Verify disk space availability.

==== code 10046: "file: <file name> - set no cache returned: <message>"

Apple/iOS only.
Setting of the redo log file to no cache mode failed.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted.
Check operating system log messages.

==== code 10009: "file: <file name> - failed to open after <number> tries"

The file couldn't be opened after several attempts.
Verify if the file exists and has the correct permissions.
Verify folder read permissions if file is to be read.

==== code 10010: "file: <file name> - unlink returned: <error>"

File remove failed.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted and contains correct JSON content.
Verify operating system log messages and filesystem integrity.

==== code 10011: "file: <file name> - seek returned: <error>"

File seek failed.
Verify if the file exists and has the correct permissions.
Verify operating system log messages and filesystem integrity.

==== code 10012: "directory: <directory name> - can't read"

Reading the contents of the directory failed.
Verify if the directory exists and has the correct permissions.
Verify operating system log messages and filesystem integrity.

==== code 10013: "spawning thread: <thread name>"

Thread creation failed.

TIP: Verify if there is a limit set in the OS related to the number of threads.

==== code 10014: "stacktrace for thread: <thread id>"

Stacktrace for thread is printed.
This message is printed when the program is terminated by a signal.

TIP: Stacktrace can be forced by sending SIGUSR1 signal to the program.

==== code 10015: "caught signal: <signal name>"

This message is printed when the program is terminated by a signal.

==== code 10016: "couldn't allocate <number> bytes memory for: <module>"

Memory allocation failed.
Verify if the provided `min-mb` and `max-mb` parameters are correct and match amount of memory available in the operating system.

==== code 10017: "out of memory"

Configured amount of memory doesn't allow processing provided stream of redo log files.
Refer to suggestions for details about reducing xref:../user-manual/user-manual.adoc#memory-allocation[memory allocation].

TIP: Increase `max-mb` parameter to allow more memory to be used.

==== code 10018: "memory allocation failed: <message>"

Memory allocation from heap failed.
Verify if the host contains enough memory to run the program.
If the problem persists, please report this issue.

IMPORTANT: Some memory structures are allocated adhoc and not from the pool defined with `min-mb` and `max-mb` parameters.
For example for storing schema (copy of content of database `SYS.*` tables).
This message is printed when such allocation fails.

==== code 10019: "binaries are build with no regex implementation, check if you have gcc version >= 4.9"

The code is compiled using the old GCC compiler which technically has regex support, but it is not complete.
Use GCC version 4.9 or newer.

The program starts at startup if regex support actually works.

==== code 10020: "program is run as root, you should never do that"

The program is run as root.
It is not recommended to run the program as root.
Run the program as a normal user.

NOTE: Although technically it should be possible to run a program as root user, this should never be done even for testing environment.
The program is designed to run as a normal user.
Running a root user may cause security issues.
Even for development or test environments, keep the program running as a normal user.

==== code 10021: "database not in ARCHIVELOG mode"

The source database must be running in ARCHIVELOG mode.
Verify if the database is running in xref:../installation/installation.adoc#database-configuration[ARCHIVELOG mode].

==== code 10022: "SUPPLEMENTAL_LOG_DATA_MIN missing

The database is missing minimal supplemental log information.
Verify that the database is xref:../installation/installation.adoc#database-configuration[configured correctly].

==== code 10023: "no data in SYS.V_$DATABASE"

Reading `SYS.V_$DATABASE` returned no data.
Verify that the database user has grants to read `SYS.V_$DATABASE` system table.
Refer to database documentation for more information.

==== code 10024: "can't position by time for standby database"

The database is a standby database.
The database must be a primary database when time defines starting position.
Start replication when the database is primary and later switch to xref:../user-manual/user-manual.adoc#dataguard[the standby database].

==== code 10025: "can't find scn for: <timestamp>"

The database function `TIMESTAMP_TO_SCN` failed to convert provided timestamp to SCN.
Replication is defined to start from a specific timestamp, but the provided timestamp value is not accepted by the database.
Verify if the timestamp is correct.

==== code 10026: "can't position by relative time for standby database"

The database is a standby database.
The database must be a primary database when relative time defines starting position.
Start replication when the database is primary and later switch to xref:../user-manual/user-manual.adoc#dataguard[the standby database].

==== code 10027: "can't read any member of group <number>"

For a given group of online redo logs, no file is available to read.
Verify if path mapping is correctly configured and files are available for reading from the location where OpenLogReplicator is running.
Verify file and path permissions/ownership.

==== code 10028: "starting sequence is unknown"

Program started with `offline` reader type but no starting sequence is available.
Verify parameters for replication start.

==== code 10029: "can't find database current scn"

Executing a query to read current SCN from a database failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10030: "getting database sequence for scn: <scn"

Executing a query to read the current database sequence value for provided SCN failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10031: "getting database scn"

The operation of determining the starting SCN failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].
Report this issue if the problem persists.

==== code 10032: "can't get parameter value for <parameter>"

Reading of database parameter failed.
Verify if the parameter exists and has the correct value.

==== code 10033: "can't get property value for <property>"

Reading of database property failed.
Verify if the property exists and has the correct value.

==== code 10034: "grants missing for table <table>"

Verify if the database user has grants to read the provided table.
Refer to database documentation for more information.

TIP: Verify if the grant script was executed successfully.

==== code 10035: "can't read <information> from flashback, provide a valid starting SCN value"

During startup when `online` reader is chosen the full schema must be read from the database.
To achieve full consistency, all database queries use flashback to read the contents of system tables for the provided SCN number.
The flashback query failed.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

TIP: Run initial replication of replication during a less active period

TIP: Run initial replication on a copy of the database which is not modified

TIP: Provide starting SCN number less away in time.
The SCN number must be within the retention period of the database.

==== code 10036: "failed to find standby redo log files"

The database is running as standby, but the list of standby redo log files couldn't be read from the database.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10037: "failed to find online redo log files"

The list of online redo log files couldn't be read from the database.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10038: "unknown database role: <role>"

Data read from system dictionaries is invalid.
Please report this issue.

==== code 10039: "updating of online redo logs failed for <path>"

Updating the list of online redo log files failed.
Verify if the files exist and have the correct permissions.

==== code 10040: "schema file missing"

Program started with `offline` reader type but no schema file is available.
Verify if the schema file exists and has the correct permissions.

==== code 10041: "table <table> - couldn't find all column sets (<keys>)"

One of the columns defined as a primary key is not present in the table definition.
Verify if the table definition is correct.

==== code 10042: "unsupported NLS_CHARACTERSET value: <value>"

Character set defined in the database is invalid.
Please report this issue.

==== code 10043: "after mapping path length (<number>) is too long for: <path>"

Provided configuration for a mapping path is too long.
Verify if the path is correct.
Verify `path-mapping` configuration parameter.

TIP: If still the problem persists and just you expect to have a so extraordinary long path which would exceed the limit of length, please report this issue.

==== code 10044: "missing location of archived redo logs for offline mode"

When starting with offline mode, it is expected that the checkpoint file contains the location of archived redo logs.
Verify if the checkpoint file contains the location of archived redo logs.

==== code 10045: "resetlogs (<resetlogs>) not found in incarnation list"

The given resetlogs value is not found in the list of available incarnations.
Verify if the resetlogs value is correct.
Verify the content of the checkpoint file.

==== code 10046: "unsupported NLS_NCHAR_CHARACTERSET value: <value>"

National character set defined in the database is invalid.
Please report this issue.

==== code 10047: "archive log processing returned: <message>, code: <number>"

Processing of archived redo log file failed.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted.

==== code 10048: "read archived redo log, code: <number>"

An unknown error appeared during processing of archived redo log file.
Please report this issue.

==== code 10049: "read online redo log, code: <number>"

An unknown error appeared during processing of online redo log file.
Please report this issue.

==== code 10050: "can't initialize oracle environment (OCI)"

Initialization of Oracle environment failed.
Check if the Oracle client is installed and configured correctly.

==== code 10051: "OCI: <message>"

Database connection error.
Verify if the database xref:../troubleshooting/troubleshooting.adoc#database-availability[is available].

==== code 10052: schema file missing

Schema is missing for batch mode.

TIP: If you don't have an earlier schema but wish to continue having no information about column names and types, try with schemaless mode (`'flags': 2`).
Refer to the documentation for more information about
xref:../user-manual/user-manual.adoc#schemaless-mode[schemaless mode].

==== code 10053: "network receive error"

Network operation of receiving data from a client failed.
Verify if the network is available and if the network is not overloaded.

==== code 10054: "network send error"

Network operation of sending data to a client failed.
Verify if the network is available and if the network is not overloaded.

==== code 10055: "message from client is incomplete (length: <number>, buffer size: <number>)"

The message received from a client is incomplete.
Verify if the network is available and if the network is not overloaded.

==== code 10056: "host disconnected"

The client has closed network connection.
Verify if the network is available and if the network is not overloaded.

==== code 10057: "Kafka: fatal error: <message>, reason: <message>"

Kafka library returned a fatal error.
Verify if the Kafka server is available and if the network is not overloaded.

==== code 10058: "Kafka failed to create configuration"

Kafka configuration can't be created.
Check if the configuration file contains valid content.

==== code 10059: "Kafka message: <message>"

Kafka library returned error during initialization.
Verify provided Kafka parameters.

==== code 10060: "Kafka failed to create producer, message: <message>"

Kafka producer creation failed.
Verify the provided Kafka parameters.

==== code 10061: "network error, errno: <number>, message: <message>"

Network error appeared during sending or receiving data.
Verify if the network is available and if the network is not overloaded.

==== code 10062: "connection to <uri> failed, errno: <number>, message: <message>"

Network connection failed.
Verify if the network is available and if the network is not overloaded.

==== code 10063: "ZeroMQ connect to <uri> failed, message: <message>"

Client can't connect to ZeroMQ server.
Verify if the ZeroMQ server is available and if the network is not overloaded.

==== code 10064: "ZeroMQ bind to <uri> failed, message: <message>"

Server can't bind to ZeroMQ socket.
Verify if the ZeroMQ server is available and if the network is not overloaded.
Verify if another process is not running on the same port.

==== code 10065: "ZeroMQ context creation failed"

Creation of ZeroMQ context failed.
Verify if the ZeroMQ library is installed and available.

==== code 10066: "ZeroMQ initializing socket failed, message: <message>"

Initialization of ZeroMQ socket failed.
Verify if the ZeroMQ library is installed and available.

==== code 10067: "out of memory, but there are reusable memory chunks, trying to reuse some memory"

The module which builds output stream is out of memory.
Stream building is suspended until memory is released.
If possible, configure higher memory limits.

==== code 10068: "invalid DBTIMEZONE value: <value>"

Database parameter `DBTIMEZONE` has an invalid value.
Please report this issue.

==== code 10069: "invalid timestamp value: <value>"

Timestamp value is invalid. Please report this issue.

==== code 10070: "invalid environment variable OLR_LOG_TIMEZONE value: <value>"

The value of environment variable `OLR_LOG_TIMEZONE` is invalid.

=== Data exceptions (2xxxx)

Errors related to syntax and content of configuration file and checkpoint files.

==== code 20001: "file: <file name> - <message>"

Parsing configuration file failed.
Check if the file is not corrupted.
Verify the content of JSON file using online JSON validator.

If the checkpoint file belongs to another database, verify if the database name is correct.

Having an incorrect checkpoint file makes it impossible to start replication.
If it is not possible to fix the checkpoint file, remove it and start replication from the beginning.

==== code 20002: "bad XID value: <text>"

Transaction ID (XID) number is in incorrect format provided in the configuration file.
This value has a wrong format and can't be parsed.
Check if the file is not corrupted.
Refer to the documentation for more information about xref:../reference-manual/reference-manual.adoc#skip-xid[XID format].

==== code 20003: "file: <file name> - parse error, field <field> <message>"

Parsing of a JSON file failed.
The file contains invalid data.
Verify if file content is a valid JSON.

==== code 20004: "identifier '<name>' is too long"

Identifier used for metadata for table or owner name is too long.
Verify if the name is correct.
Verify if the name is not too long.

==== code 20005: "file: <file name> - <field name> should be an array with 2 elements"

Checkpoint file contains invalid data.
Verify if file content is a valid JSON.

==== code 20006: "file: <file name> - invalid offset: <number> is not a multiplication of 512"

The file is not a valid archived redo log file.
Verify if the file exists and has the correct permissions.
Verify if the file is not corrupted and contains correct JSON content.

==== code 20007: "file: <file name> - <schema> is [missing|redundant]"

After starting of replication and collecting schema file, OpenLogReplicator monitors all tables in the database such match defined schema and user mask.
If replication is stopped, the configuration file should not be altered and new schemas can't be added to the list of replicated tables.
If such an event happens, replication can't start, and the following message is printed.
This error reports that either a schema is missing or is redundant compared to the main configuration file (OpenLogReplicator.json).

==== code 20008: "row ID incorrect length: <number>"

Row ID is in incorrect format.
The length of the row ID is not correct.
Verify if the row ID is correct.

=== Configuration errors (3xxxx)

Parameters defined to start OpenLogReplicator have incorrect values.

==== code 30001: "bad JSON, invalid '<field name>' value: <observed value>, expected <expected value>"

The value of the field is not correct.
Check if the file contains valid content.

==== code 30002: "invalid arguments, run: <binary name> [-v|--version] or [-f|--file CONFIG] default path for CONFIG file is <file name>"

Invalid arguments were passed to the program.
Check if the program was started correctly.

==== code 30003: "owner '<name>' contains lower case characters, value must be upper case"

Table owner contains lower case characters.
Table owner must be in the upper case.
Please report this issue.

==== code 30004: "table '<name>' contains lower case characters, value must be upper case"

Table name contains lower case characters.
Table owner must be in the upper case.
Please report this issue.

==== code 30005: "invalid value for 'output': <value>"

Syntax error in `output` parameter.
Verify if the parameter is correct.
Probably there is a single `%` character but not followed by proper format.

==== code 30006: "output file is with no rotation: <value> - 'append' must be set to 1"

File name is defined as a static file name without rotation.
For such cases the `append` parameter must be set to 1.

==== code 30007: "output file is with no max file size: <output> - 'max-file-size' must be defined for output with rotation"

File is defined with rotation but no maximum file size is set.
Define `max-file-size` parameter.

==== code 30008: "uri is missing ':' in parameter: <parameter>"

URI is missing a `':'` character.
Verify if the URI is correct.

==== code 30009: "Kafka property '<name>' is defined multiple times"

One of the parameters for Kafka writer is defined twice.

==== code 30010: "Kafka property 'message.max.bytes' is defined, but it is not allowed to be set by user"

This property defines the size of maximum message size.
This parameter is already defined by parameter "max-message-mb" and should not be defined explicitly using Kafka connection parameter.

=== Redo log errors (4xxxx)

Some data in redo log files aren't correct.
The data doesn't need the model requirements of OpenLogReplicator or is corrupted.

==== code 40001: "file: <file name> block: <number> - invalid block size: <number>, header[1]: <number>"

Block size in the header of the file doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40002: "file: <file name> - invalid header block number: <number>, expected: <number>"

Block number doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40003: "file: <file name> - invalid header[0]: <number>"

Invalid header read from the file.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40004: "file: <file name> - invalid header[28-31]: <number>, <number>, <number>, <number>"

Invalid header read from the file.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40005: "file: <file name> - invalid block size: <number>, header[1]: <number>"

Block size in the header of the file doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40006: "file: <file name> - invalid database version: <number>"

The database version in the header of the file doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40007: "file: <file name> - invalid database version: <number>, expected: <number>"

The database version in the header of the block doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40008: "file: <file name> - invalid first scn value: <number>, expected: <number>"

The first scn value reported in the header of the block doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40009: "file: <file name> - invalid next scn value: <number>, expected: <number>"

The next scn value reported in the header of the block doesn't match the expected value.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

==== code 40010, "file: <file name> - zero to read, start: <number>, end: <number>, scan: <number>"

Double read error.
Verify if the file is not corrupted.
If the problem persists, please report this issue.

=== Internal errors (5xxxx)

Provided below is a list of internal errors which should never appear.
If you encounter any of these errors, please report this issue.

==== code 50001: "trying to free unknown memory block for: <module>"

==== code 50002: "trying to insert table: <owner>.<name> (obj: <number>, dataobj: <number>) column: <name> (col#: <number>, segcol#: <number>) on position <number>"

==== code 50003: "inconsistent page size lobid: <lobid>, new: <number>, already set to: <number>, xid: <xid>, offset: <number>"

==== code 50004: "duplicate index lobid: <lobid>, page: <number>, already set to: <number>, xid: <xid>, offset: <number>"

==== code 50005: "field size out of vector, field: <number>/<number>, pos: <number>, size: <number>, max: <number>, code: <number>"

==== code 50006: "field missing in vector, field: <number>/<number>, ctx: <number>, obj: <number>, dataobj: <number>, op: <code>, cc: <number>, suppCC: <number>, fieldLength: <number>, code: <number>"

==== code 50007: "field size out of vector, field: <number>/<number>, pos: <number>, size: <number>, max: <number>, code: <number>"

==== code 50008: "field size out of vector: field: <number>/<number>, pos: <number>, size: <number>, max: <number>"

==== code 50009: "error parsing numeric value at offset: <number>"

==== code 50010: "can't find character set map for id = <number> at offset: <number>"

==== code 50011: "got character code: U+<number> at offset: <number>"

==== code 50012, "trying to allocate length for value: <number> exceeds maximum: <number> at offset: <number>"

==== code 50013: "trying to output null data for column: <name>, offset: <number>"

==== code 50014: "table: <table>: out of columns (<group>): <number/<number>, <number>, <number>-<number>-<number>, xid: <xid>, offset: <number>"

==== code 50015: "value for <number>/<number> is already set when merging, xid: <xid>, offset: <number>"

==== code 50016: "PB <operation> processing failed, message already exists"

==== code 50017: "PB <operation> processing failed, error serializing to string

==== code 50018: "PB <operation> processing failed, a message is missing

==== code 50019: "ddl: column type mismatch for <owner>.<table>: column <column> type found <type> offset: <number>"

==== code 50020: "ddl: column type mismatch for <owner>.<table>: column <column> value found <value> offset: <number>"

==== code 50021: "incorrect conversion of string: <string>"

==== code 50022: "ddl: duplicate <owner>.<table>: (rowid: <rowid>) for insert at offset: <number>"

==== code 50023: "duplicate <owner>.<table> value: (rowid: <rowid>)"

==== code 50024: duplicate value for unique (<columns>)

==== code 50025: "value of <owner>.<table> too <condition> (<details>)"

==== code 50026: "table <table>.<owner> - unsupported character set id: <charset> for column: <column>"

==== code 50027: "table <owner>.<name> couldn't find obj for lob <number>"

==== code 50028: "table <owner>.<name> couldn't find obj for lob frag <number>"

==== code 50029: "<structure> not empty, left: <number> at exit"

==== code 50030: "missing index for <owner>.<table> (<columns>)"

==== code 50031: "can't add table (obj: <number>, dataobj: <number>)"

==== code 50032: "can't add lob index element (dataobj: <number>)"

==== code 50033: "can't add partition (obj: <number>, dataobj: <number>)"

==== code 50034: "can't add partition element (obj: <number>, dataobj: <number>)"

==== code 50035: "can't remove partition (obj: <number>, dataobj: <number>)"

==== code 50036: "can't remove table partition element (obj: <number>, dataobj: <number>)"

==== code 50037: "can't remove lob index element (dataobj: <number>)"

==== code 50038: "can't remove table (obj: <number>, dataobj: <number>)"

==== code 50039: "transaction <xid>> conflicts with <xid>"

==== code 50040: "block size (<number>) exceeding max block size (<number>), try increasing the FULL_BUFFER_SIZE parameter"

==== code 50041: "bad split offset: <number> xid: <xid>"

==== code 50042: "split undo HEAD no 5.1 offset: <number>"

==== code 50043: "bad split offset: <number> xid: <xid>" second position

==== code 50044: "trying to remove from empty buffer size: <number> elements: <number>"

==== code 50045: "bdba does not match (<value>, <value>), offset: <number>"

==== code 50046: "block: <block>, offset: <number>: <message>"

==== code 50047: "incorrect offset start: <number> - not a multiplication of block size: <size>"

==== code 50048: "invalid resetlogs value (found: <value>, expected: <value>): <file name>"

==== code 50049: "invalid lwn scn: <scn>"

==== code 50050: "invalid lwn max: <value>/<value>/<value>"

==== code 50051: "did not find lwn at offset: <value>"

==== code 50052: "all <number> lwn buffers allocated"

==== code 50053: "too big redo log record, length: <number>"

==== code 50054: "all <number> records in lwn were used"

==== code 50055: "lwn overflow: <number>/<number>"

==== code 50056: "system transaction already active"

==== code 50057: "unknown op code <number>, offset: <number>"

==== code 50058: "output buffer - commit of empty transaction"

==== code 50059: "table: <table>: invalid column shift: <number>, before: <number>, xid: <xid>, offset: <number>"

==== code 50060: "table: <table>: referring to invalid column id(<number>), xid: <xid>, offset: <number>"

==== code 50061: "too short field <code>: <number> offset: <number"

==== code 50062: "non-free blocks in transaction buffer: <number>"

==== code 50063: "nulls field is missing on offset: <number>"

==== code 50064: "attributes with no transaction, offset: <number>"

==== code 50065: "empty attributes for XID: <xid>"

==== code 50066: "invalid expression evaluation: <message>"

==== code 50067: "invalid condition: <message>"

==== code 50068: "missing <table> table, <operation> failed"

==== code 50069: "no active XML context found"

The experimental feature to decode binary xmldata has been turned on, but the metdata contains no xml dictionary data.
Please consider recreating schema checkpoint files: stop replication, delele content of checkpoint folder, and restart to recreate the schema file.

== Warnings Messages

=== Warnings (6xxxx)

==== code 60001: "incomplete row for table (obj: <number>), probably IOT, xid: <xid>, offset: <number>"

This warning is most probably related to using schemaless mode with IOT tables.
In this case, please try to use schema mode instead.
If the problem persists, please report this issue.

==== code 60002: "unknown value (column: <column>): <number> - <data>)"

Might be related to extensive using of dbms_lob package.
In this case, please try to use direct DML operations for LOB columns instead.
If the problem persists, please report this issue.

==== code 60003: "incorrect LOB for xid: <xid>, data: <data>, location: <number>"

See comment for warning 60002.

==== code 60004: "can't find page <number> for xid: <xid>, LOB: <lob>, obj: <number>"

See comment for warning 60002.

==== code 60005: "missing LOB data (new in-value) for xid: <xid,> LOB: <lob>, page: <number>, obj: <number>"

See comment for warning 60002.

==== code 60006: "dump LOB: <lob> data: <data>"

See comment for warning 60002.

==== code 60007: "incorrect LOB sum xid: <xid> left: <number> obj: <number>"

See comment for warning 60002.

==== code 60008: "can't decode character: (x, y, z) using character set <name>, xid: <xid>"

The character field contained a character code which is invalid and can't be decoded.
If the field is not character, and the data is expected to be correct, please report this issue.

==== code 60009: "duplicate orphaned lob: <lob>, page: <number>"

See comment for warning 60002.

==== code 60010: "no match found for transaction rollback, skipping, SLT: <number>, USN: <number>"

This warning could appear during replication startup.
It means that the beginning of the transaction appeared probably before replication startup.

==== code 60011: "skipping transaction with no beginning: <details>"

Received commit for a transaction which started before replication startup.
The transaction is discarded.

==== code 60012: "aborting log dump"

The log dump is aborted because there was a problem with creating a file for the dump.

==== code 60013: "forced to continue working in spite of error"

In spite of redo log data error, the redo log is processed.
A message has been printed with the error which appeared during parsing.
Investigate the error anyway and verify if the data is correct.

==== code 60014: "verify redo log file for OP:10.8, len: <number>, data = [<number>, <number>, <number>, <number>]"

See comment for warning 60002.

==== code 60015: "big transaction divided (forced commit after <number> bytes), xid: <xid>"

A huge transaction has exceeded provided maximum size for transactions.

==== code 60016: "LOB is null for (obj: <number>, dataobj: <number>), offset: <number>>, xid: <xid>"

See comment for warning 60002.

==== code 60017: "minimal supplemental log missing or redo log inconsistency for transaction <xid>"

Verify if supplemental logging is enabled for the database.
If it is, and even after log switch the warning appears, please report this issue.

==== code 60018: "file: <file name> - couldn't write checkpoint"

Checkpoint file couldn't be created because of errors.
Verify the reason and try to fix it.

==== code 60019: "file: <file name> - load checkpoint failed, reference SCN missing"

Schema missing in checkpoint file.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60020: "file: <file name> - load adaptive schema failed"

Adaptive schema load failed.
The program will continue without any schema.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60021: "missing LOB index for LOB (OBJ#: <number>, DATAOBJ#: <number>, COL#: <number>)"

See comment for warning 60002.

==== code 60022: "missing TS#: <number>, BLOCKSIZE: <number>"

Missing information about tablespace in the database schema.
Verify if the tablespace is correct.
If the problem persists, please report this issue.

==== code 60023: "file: <file name> position: <number> - unexpected end of file"

Unexpected end of redo log file.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60024: "file: <file name> - invalid header sequence (<number>, expected: <number>)"

Invalid information about a redo log sequence in the header.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60025: "file: <file name> block: <number> - invalid header checksum, expected: <number>, calculated: <number>"

Invalid checksum in the redo log header.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60026: "stripping trailing '/' from <name> parameter; new value: <value>"

Stripped trailing '/' from the parameter value from the path parameter.

==== code 60027: "couldn't find archive log for seq: <number>, found: <number>, sleeping <number> us"

Missing archive log file.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60028: "can't get sequence from file: <file name> log_archive_format: <string> at position <number> format position <number>, <problem>"

Invalid archive log file name.
Verify if the file is correct.
If the problem persists, please report this issue.

==== code 60029: "message size (<number>) will exceed 'max-file-size' size (<number>)"

The defined maximum size for the file is too small to write a single message.
Increase the size.

==== code 60030: "rotation size is set too low (<number>), increase it, should rotate but too early (<file name>)"

The parameter for rotation size is too small.
Increase the number.

==== code 60031: "queue, full, sleeping <number> >ms, then retrying"

The queue for redo log data is full.
The program will sleep for a while and then retry.
Investigate the reason why the receiver is not able to process the data fast enough.

==== code 60032: "unknown request code: <message>"

Invalid request code received by the network client.

==== code 60033: "request decoder[<number>]: <data>"

Invalid request data received by the network client.

==== code 60034: "file: <file name> - stat returned: <message>"

Reading file metadata failed.
Check if the file is not corrupted.
Verify operating system log messages.

==== code 60035, "unknown database requested, got: <name>, expected: <name>"

The client requested a database which is not configured in the program.

==== code 60036, "incorrect XML data: <message>"

Data for XMLTYPE column type is not correct.

==== code 60037, "observed UPDATE operation for NOT NULL column with NULL value for table <owner>.<table> column <column>"

There could be cases that due to some upgrades from old versions or other unknown reasons, the BEFORE image for UPDATE command contains NULL value for a column that has been defied as NOT NULL.

By default, OpenLogReplicator would just print the informational message (but just once per column) and continue with the replication.

It is also possible to treat the AFTER image as the correct value and copy it to the BEFORE image of the column value.
This feature is experimental.
To achieve this behavior, the xref:../reference-manual/reference-manual.adoc#flags[flags] parameter should be set appropriately.

=== Internal warnings (7xxxx)

Provided below is a list of internal warnings which should never appear.
If you encounter any of these warnings, please report this issue.

==== code 70001: "too short field <code>: <number> offset: <number"

==== code 70002: "dumping redo vector"

==== code 70003: "trying to rollback2: <number> with: <number>, offset: <number>, xid: <xid>, pos: <number>"

==== code 70004: "rollback failed for <number> empty buffer, offset: <number>, xid: <xid>, pos: <number>"

==== code 70005: "data in SYS.CDEF$ missing for CON#: <number>"

==== code 70006: "OCI: <message>"

==== code 70007: "trying to confirm an empty message"

==== code 70008: "Kafka: <number> delivery failed: <message>"

==== code 70009: "Kafka: <message>, reason: <message>"

==== code 70010: "unknown undo OP: <number>, opc: <number>"

==== code 70011: "unknown rollback OP: <number>, opc: <opc>)

== Info messages

=== Information (8xxxx)

== Trace messages

=== Trace (9xxxx)

All trace messages are printed with code 99999.
