= OpenLogReplicator.json - state element
:author: Adam Leszczyński <aleszczynski@bersler.com>
:revnumber: 1.9.0
:revdate: 2026-01-16
:icons: font

[frame="none",grid="none"]
|====
|[.small]#Author: {author}, version: {revnumber}, date: {revdate}#
|====

This document describes the `state` configuration block used by OpenLogReplicator.
It covers checkpointing behavior, storage options, recommended defaults and operational notes.

[[state]]
[width="100%",cols="a,a,50%a",options="header"]
.State element
|===

|Parameter
|Type / constraints
|Description and notes

|`interval-mb`
|_integer_, min: 0, default: 500
|Threshold of processed redo log data after which a checkpoint file is created.

Number in megabytes.

|`interval-s`
|_integer_, min: 0, default: 600
|Threshold of processed redo log data time after which a checkpoint file is created.

Number in seconds.

_IMPORTANT:_ The time refers not to processing time by OpenLogReplicator but to time of the redo log data.
For example, the default setting of 600 seconds means that if the last checkpoint was created after processing redo log data created at 10:40 when the processing reaches data created at 10:50 new checkpoint file is created.

|`keep-checkpoints`
|_integer_, min: 0, default: 100
|Number of checkpoint files which should be kept.
The oldest checkpoint files are deleted.

_TIP:_ Value `0` disables checkpoint files deletion.

_TIP:_ Keeping a larger number of checkpoint files allows adjusting starting SCN more precisely.
It provides more security in case of filesystem corruption and the last checkpoint file not being available.

_CAUTION:_ The number of checkpoint files may be actually larger than this parameter (exactly up to `keep-checkpoints` + `schema-force-interval`).
Checkpoint file might be deleted only if it is not referred in some consecutive checkpoint files (that don't contain schema data).

|`path`
|_string_, max length: 2048, default: `"checkpoint"`
|The path to store checkpoint files.

_NOTE:_ This field is valid only for `disk` type.

_IMPORTANT:_ The path should be accessible for writing by the user which runs the program.

|`schema-force-interval`
|_number_m min: 0, default: 20
|To increase operating speed, not all checkpoint files would contain the full schema of the database.
In case the schema didn't change, it is not necessary to repeat the schema in every checkpoint file.
The value determines the consecutive number of checkpoint files which may not contain the full schema.

_TIP:_ The value of `0` means that the schema is always included in the checkpoint file.

|`type`
|_string_, max length: 256, default: `"disk"`
|Only `disk` is supported.

|===
