--Example file with list of required grants for OpenLogReplicator

GRANT SELECT ON SYS.CCOL$ TO <USER>;
GRANT SELECT ON SYS.CDEF$ TO <USER>;
GRANT SELECT ON SYS.COL$ TO <USER>;
GRANT SELECT ON SYS.CON$ TO <USER>;
GRANT SELECT ON SYS.OBJ$ TO <USER>;
GRANT SELECT ON SYS.TABCOMPART$ TO <USER>;
GRANT SELECT ON SYS.TABPART$ TO <USER>;
GRANT SELECT ON SYS.TABSUBPART$ TO <USER>;
GRANT SELECT ON SYS.TAB$ TO <USER>;
GRANT SELECT ON SYS.USER$ TO <USER>;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO <USER>;
GRANT SELECT ON SYS.V_$DATABASE_INCARNATION TO <USER>;
GRANT SELECT ON SYS.V_$DATABASE TO <USER>;
GRANT SELECT ON SYS.V_$LOGFILE TO <USER>;
GRANT SELECT ON SYS.V_$LOG TO <USER>;
GRANT SELECT ON SYS.V_$PARAMETER TO <USER>;
GRANT SELECT ON SYS.V_$TRANSPORTABLE_PLATFORM TO <USER>;
