// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: OraProtoBuf.proto

#include "OraProtoBuf.pb.h"
#include "OraProtoBuf.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace OpenLogReplicator {
namespace pb {

static const char* OpenLogReplicator_method_names[] = {
  "/OpenLogReplicator.pb.OpenLogReplicator/Redo",
};

std::unique_ptr< OpenLogReplicator::Stub> OpenLogReplicator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OpenLogReplicator::Stub> stub(new OpenLogReplicator::Stub(channel));
  return stub;
}

OpenLogReplicator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Redo_(OpenLogReplicator_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>* OpenLogReplicator::Stub::RedoRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>::Create(channel_.get(), rpcmethod_Redo_, context);
}

void OpenLogReplicator::Stub::experimental_async::Redo(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::OpenLogReplicator::pb::RedoRequest,::OpenLogReplicator::pb::RedoResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::OpenLogReplicator::pb::RedoRequest,::OpenLogReplicator::pb::RedoResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Redo_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>* OpenLogReplicator::Stub::AsyncRedoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>::Create(channel_.get(), cq, rpcmethod_Redo_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>* OpenLogReplicator::Stub::PrepareAsyncRedoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>::Create(channel_.get(), cq, rpcmethod_Redo_, context, false, nullptr);
}

OpenLogReplicator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenLogReplicator_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< OpenLogReplicator::Service, ::OpenLogReplicator::pb::RedoRequest, ::OpenLogReplicator::pb::RedoResponse>(
          [](OpenLogReplicator::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::OpenLogReplicator::pb::RedoResponse,
             ::OpenLogReplicator::pb::RedoRequest>* stream) {
               return service->Redo(ctx, stream);
             }, this)));
}

OpenLogReplicator::Service::~Service() {
}

::grpc::Status OpenLogReplicator::Service::Redo(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::OpenLogReplicator::pb::RedoResponse, ::OpenLogReplicator::pb::RedoRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace OpenLogReplicator
}  // namespace pb

