// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: OraProtoBuf.proto

#include "OraProtoBuf.pb.h"
#include "OraProtoBuf.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace OpenLogReplicator {
namespace pb {

static const char* RedoStream_method_names[] = {
  "/OpenLogReplicator.pb.RedoStream/redoStream",
};

std::unique_ptr< RedoStream::Stub> RedoStream::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RedoStream::Stub> stub(new RedoStream::Stub(channel));
  return stub;
}

RedoStream::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_redoStream_(RedoStream_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>* RedoStream::Stub::redoStreamRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>::Create(channel_.get(), rpcmethod_redoStream_, context);
}

void RedoStream::Stub::experimental_async::redoStream(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::OpenLogReplicator::pb::Request,::OpenLogReplicator::pb::Redo>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::OpenLogReplicator::pb::Request,::OpenLogReplicator::pb::Redo>::Create(stub_->channel_.get(), stub_->rpcmethod_redoStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>* RedoStream::Stub::AsyncredoStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>::Create(channel_.get(), cq, rpcmethod_redoStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>* RedoStream::Stub::PrepareAsyncredoStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>::Create(channel_.get(), cq, rpcmethod_redoStream_, context, false, nullptr);
}

RedoStream::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RedoStream_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RedoStream::Service, ::OpenLogReplicator::pb::Request, ::OpenLogReplicator::pb::Redo>(
          [](RedoStream::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::OpenLogReplicator::pb::Redo,
             ::OpenLogReplicator::pb::Request>* stream) {
               return service->redoStream(ctx, stream);
             }, this)));
}

RedoStream::Service::~Service() {
}

::grpc::Status RedoStream::Service::redoStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::OpenLogReplicator::pb::Redo, ::OpenLogReplicator::pb::Request>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace OpenLogReplicator
}  // namespace pb

